export const REACT_APP_BASE_URL = process.env.REACT_APP_BASE_URL;
export const REACT_APP_VALUATION_URL = process.env.REACT_APP_VALUATION_URL;
export const REACT_APP_PLAYER_LIST_URL = process.env.REACT_APP_PLAYER_LIST_URL;
